import { useParams } from "react-router"
import { Calendar, Code, Tag, ShieldCheck } from "lucide-react"

import { PageContainer } from "@/components/common/PageContainer"
import { ErrorState } from "@/components/common/ErrorState"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"

import { useWorkflowVersion } from "../hooks/useWorkflowVersion"
import { WorkflowHeader } from "../components/WorkflowHeader"
import { WorkflowSkeleton } from "../components/WorkflowSkeleton"

export const WorkflowVersionPage = () => {
  const { workflowId, versionId } = useParams<{ workflowId: string; versionId: string }>()

  const wId = workflowId || ""
  const vId = versionId || ""

  const { data, isLoading, isError, refetch } = useWorkflowVersion(wId, vId)

  if (isLoading) {
    return <WorkflowSkeleton />
  }

  if (isError || !data?.data) {
    return (
      <PageContainer>
        <WorkflowHeader
          title="Version Details"
          backLink={`/workflows/${wId}`}
          backText="Back to Workflow"
        />
        <ErrorState
          title="Version data unavailable"
          message="Failed to load version details. Please verify your connection."
          onRetry={refetch}
        />
      </PageContainer>
    )
  }

  const version = data.data

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString(undefined, {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  return (
    <PageContainer>
      <WorkflowHeader
        title={`Version v${version.versionNumber}`}
        description="Inspect release parameters and configuration builder definitions."
        backLink={`/workflows/${wId}`}
        backText="Back to Workflow Details"
      />

      <div className="grid gap-6 md:grid-cols-3">
        {/* Version metadata parameters */}
        <div className="md:col-span-1 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg font-bold flex items-center gap-2">
                <Tag className="h-5 w-5 text-primary" /> Version Metadata
              </CardTitle>
              <CardDescription>System properties for this release.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
              <div className="flex justify-between border-b border-border pb-2">
                <span className="text-muted-foreground">Version ID</span>
                <span className="font-mono text-xs text-muted-foreground bg-muted px-2 py-0.5 rounded">
                  {version.id}
                </span>
              </div>

              <div className="flex justify-between border-b border-border pb-2">
                <span className="text-muted-foreground">Release status</span>
                <span>
                  {version.isPublished ? (
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                      <ShieldCheck className="h-3.5 w-3.5" /> Published Release
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-500/10 text-amber-600 dark:text-amber-400">
                      Draft Release
                    </span>
                  )}
                </span>
              </div>

              <div className="flex justify-between">
                <span className="text-muted-foreground flex items-center gap-1">
                  <Calendar className="h-4 w-4" /> Created Date
                </span>
                <span className="text-muted-foreground">{formatDate(version.createdAt)}</span>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Code Definition block */}
        <div className="md:col-span-2">
          <Card className="h-full flex flex-col">
            <CardHeader className="border-b border-border">
              <CardTitle className="text-lg font-bold flex items-center gap-2">
                <Code className="h-5 w-5 text-primary" /> Definition Schema
              </CardTitle>
              <CardDescription>
                Raw JSON nodes and edges definition generated by the workflow builder.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex-1 p-0 bg-zinc-950 dark:bg-black/40 rounded-b-xl overflow-hidden min-h-[350px] relative">
              <pre className="p-6 text-xs font-mono text-emerald-400 dark:text-emerald-300 overflow-auto max-h-[500px] select-all leading-relaxed whitespace-pre-wrap">
                {JSON.stringify(version.definition, null, 2)}
              </pre>
            </CardContent>
          </Card>
        </div>
      </div>
    </PageContainer>
  )
}
